### ISSUE TITLE
Possibility to disable ANIMATABLE_XWALK_VIEW via config.xml

### ISSUE THREAD

**Issue by Delagen** [infil00p/cordova-crosswalk-engine#13]
Always enabled

``` java
boolean prefAnimatable = preferences == null ? false : preferences.getBoolean("CrosswalkAnimatable", false);
            boolean manifestAnimatable = ai.metaData == null ? false : ai.metaData.getBoolean("CrosswalkAnimatable");
            if (prefAnimatable || manifestAnimatable) {
                // Slows it down a bit, but allows for it to be animated by Android View properties.
                XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, true);
            }
```

**Comment by fujunwei** [comment]
The new repo of pluggable Crosswalk webview is https://github.com/MobileChromeApps/cordova-plugin-crosswalk-webview.
Could you please send a PR to it.

**Comment by Delagen** [comment]
In this repository no Issues can be created. So cannot

**Comment by chernobil** [comment]
Is there any progress about this issue ?

**Comment by Delagen** [comment]
In this repository no Issues can be created. So no progress

**Comment by chernobil** [comment]
Hahahaha the repository system is  working as good as the cordova-crosswalk integration i guess .

**Comment by Delagen** [comment]
If you know how to post issue to crosswalk-project/cordova-plugin-crosswalk-webview tell me )

**Comment by chernobil** [comment]
(like). I think that they've disabled that section on purpose there - no issue logging section => no issue => everything is working as expected => everyone is happy .

**Comment by fujunwei** [comment]
Sorry for later reply. This issue have fixed in the repo of https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/. Could you please try to again.

**Comment by Delagen** [comment]
I see no changes. Could you provide link to commit or any docs how to disable?
No I am manually add line 
```
XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, false);
```
to the end of method

**Comment by fujunwei** [comment]
Yes, we want to disable it in Crosswalk by default, the plugin has a option to enable the animation.

**Comment by Delagen** [comment]
Animation provides some glitches in view, so I was needed to disable it to provide predicted user experience

**Comment by baleboy** [comment]
for various reasons, in the Crosswalk Project we've chosen to use JIRA (https://crosswalk-project.org/jira/) to track issues rather than Github's own issue tracker. That's why we disabled issue tracking in the Crosswalk Project repositories, no conspiracies here :)
