### ISSUE TITLE
cordova pause resume events dont fire

### ISSUE THREAD

**Issue by northkode** [infil00p/cordova-crosswalk-engine#14]
how can i get back the native pause and resume events when exiting the app?
They dont seem to fire with this..

**Comment by fujunwei** [comment]
Could you please try to use `document.addEventListener("pause", yourCallbackFunction, false);`

**Comment by fujunwei** [comment]
The new repo of pluggable Crosswalk webview is  https://github.com/MobileChromeApps/cordova-plugin-crosswalk-webview, thanks.

**Comment by northkode** [comment]
I have that code in place and doesn't work.

Also the new repo doesn't accept issues so I can't let that developer know.

kyle

**Comment by ms88privat** [comment]
please open issues on the new repo, thank you.

**Comment by northkode** [comment]
I can't... they are disabled. I am unable to open issues on that repo. The issues tab is not available..
and the reason the events don't fire is the JSMessageQueue is broken on crosswalk.
ERROR: D/JsMessageQueue﹕ Dropping Native->JS message due to disabled bridge

**Comment by fujunwei** [comment]
Could you please try to test it without crosswalk? and which devices are you using? It would be helpful if you could provide more information to reproduce it.
