### ISSUE TITLE
Howto disable multiple apks build?

### ISSUE THREAD

**Issue by mlegenhausen** [infil00p/cordova-crosswalk-engine#24]
I tried many stuff but I was not able to disable the multiple apk build. How can I set this via the command line interface?

**Comment by mlegenhausen** [comment]
Ok found it out myself `cordova build android -- --gradleArg=-PcdvBuildMultipleApks=''` there is currently a bug where `cordova build android -- --gradleArg=-PcdvBuildMultipleApks=false` does not work as expected. See apache/cordova-android#199.

**Comment by txedo** [comment]
It is working in Cordova CLI 5.4.0.

`$ cordova build android --release -- --versionCode=6004 --gradleArg=-PcdvBuildMultipleApks=true --gradleArg=-PcdvBuildArch=x86`

**Comment by mlegenhausen** [comment]
My pull request was merged so we can close this issue.
