### ISSUE TITLE
Multiple apks builded but not actually different

### ISSUE THREAD

**Issue by enricodeleo** [infil00p/cordova-crosswalk-engine#25]
Hi!
I'm experiencing a strange behavior: until last week when I builded apks those was recognized respectively as x86 and armv7 when uploaded to the Play Store.
Now, even if I do the same tasks and I get the same two apks, those apks are recognized as compatible with all the native architecture available.

Is anything that happens just to me? Any ideas?

Thanks!

**Comment by fujunwei** [comment]
Do you mean you built two different architecture apk , but can't uploaded to the Play Store?

**Comment by enricodeleo** [comment]
When I build the app I get two flavors: x86 and arm. I can upload both the apks successfully on PlayStore but it says that both apks support all the native platform even if each one is actually build for a single architecture.

For example this is what I see on PlayStore for `android-x86-release.apk`
<img width="558" alt="screen shot 2015-07-24 at 08 21 08" src="https://cloud.githubusercontent.com/assets/3534555/8868830/fc2da50e-31dc-11e5-811b-1f09a98b3548.png">
the same happens for `android-armv7-release.apk`

**Comment by ChristiaanScheermeijer** [comment]
@enricodeleo did you already solve that issue? We are experiencing the same issue!

**Comment by fujunwei** [comment]
I have filed a bug to track it in JIRA 
https://crosswalk-project.org/jira/browse/XWALK-4970

**Comment by jingjingxli** [comment]
hi,
I verfiy this issue with these test steps:
1. $ cordova create foo com.example.foo foo
2. $cd foo 
3. $cordova platform add android
4. $ cordova plugin add ../cordova-plugin-crosswalk-webview   --->>download form https://github.com   and crosswalk version:14+
5. $ cordova build android
then $aapt d --values badging android-armv7-debug.apk
{code}
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'ca' 'da' 'fa' 'ja' 'nb' 'de' 'bg' 'th' 'fi' 'hi' 'vi' 'sk' 'uk' 'el' 'nl' 'pl' 'sl' 'tl' 'am' 'in' 'ko' 'ro' 'ar' 'fr' 'hr' 'sr' 'tr' 'cs' 'es' 'it' 'lt' 'hu' 'ru' 'lv' 'sv' 'iw' 'sw' 'en-GB' 'zh-CN' 'pt-BR' 'es-US' 'pt-PT' 'zh-TW'
densities: '120' '160' '240' '320' '480' '640'
native-code: 'armeabi-v7a'
{code}
then $aapt d --values badging android-x86-debug.apk
{code}
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'ca' 'da' 'fa' 'ja' 'nb' 'de' 'bg' 'th' 'fi' 'hi' 'vi' 'sk' 'uk' 'el' 'nl' 'pl' 'sl' 'tl' 'am' 'in' 'ko' 'ro' 'ar' 'fr' 'hr' 'sr' 'tr' 'cs' 'es' 'it' 'lt' 'hu' 'ru' 'lv' 'sv' 'iw' 'sw' 'en-GB' 'zh-CN' 'pt-BR' 'es-US' 'pt-PT' 'zh-TW'
densities: '120' '160' '240' '320' '480' '640'
native-code: 'x86'
{code}


so,can you provide crosswalk version and crodova-plugin-crosswalk-webview download form github or npm?Then i will verfiy this issue again.

**Comment by jingjingxli** [comment]
hi,
I verfiy this issue with these test steps:
1. $ cordova create foo com.example.foo foo
2. $cd foo 
3. $cordova platform add android
4. $ cordova plugin add ../cordova-plugin-crosswalk-webview   --->>download form https://github.com   and crosswalk version:14+
5. $ cordova build android
then $aapt d --values badging android-armv7-debug.apk
```
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'ca' 'da' 'fa' 'ja' 'nb' 'de' 'bg' 'th' 'fi' 'hi' 'vi' 'sk' 'uk' 'el' 'nl' 'pl' 'sl' 'tl' 'am' 'in' 'ko' 'ro' 'ar' 'fr' 'hr' 'sr' 'tr' 'cs' 'es' 'it' 'lt' 'hu' 'ru' 'lv' 'sv' 'iw' 'sw' 'en-GB' 'zh-CN' 'pt-BR' 'es-US' 'pt-PT' 'zh-TW'
densities: '120' '160' '240' '320' '480' '640'
native-code: 'armeabi-v7a'
```
then $aapt d --values badging android-x86-debug.apk
```
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'ca' 'da' 'fa' 'ja' 'nb' 'de' 'bg' 'th' 'fi' 'hi' 'vi' 'sk' 'uk' 'el' 'nl' 'pl' 'sl' 'tl' 'am' 'in' 'ko' 'ro' 'ar' 'fr' 'hr' 'sr' 'tr' 'cs' 'es' 'it' 'lt' 'hu' 'ru' 'lv' 'sv' 'iw' 'sw' 'en-GB' 'zh-CN' 'pt-BR' 'es-US' 'pt-PT' 'zh-TW'
densities: '120' '160' '240' '320' '480' '640'
native-code: 'x86'
```

**Comment by jingjingxli** [comment]
@enricodeleo can you provide the version of crosswalk and crodova-plugin-crosswalk-webview download from NPM or master when you used to builded apk?
Then we can help to reproduce  this issue.

**Comment by enricodeleo** [comment]
@jingjingxli I use the plugin at version 1.2.0, crosswalk is at version 14.43.343.24. 
I also tried to checkout the plugin from master branch and re-build this morning with --release and what I got was `native-code: 'arm64-v8a' 'armeabi' 'armeabi-v7a' 'x86' 'x86_64'`

**Comment by ChristiaanScheermeijer** [comment]
Hi @jingjingxli and @enricodeleo,

I've found the reason for this issue in our app. In previous versions we had included the following plugin `cordova-sqlite-storage` but somehow sneaked back in. This plugin adds native libraries for each specific Android architectures. Removing this plugin solved the issue!

@enricodeleo it could be possible different plugins or frameworks can cause this issue. I've detected it by unzipping a APK and look in the ./lib folder. If there are multiple folders, named by architecture, see which libraries are added in the other architecture folders. There should only be one folder named the architecture the build is for.

Cheers!

**Comment by enricodeleo** [comment]
@ChristiaanScheermeijer thank you for the hint! Checking the ./lib folder I was able to find a .so library added by SQLite Plugin. Appartently the latest versions of this plugin prevent the build phase to generate multiple apks. The only solution for now is to switching back com.brodysoft.sqlitePlugin to version r1.0.4.

Hope this feedback helps others that are experiencing the same issue.

**Comment by newjam** [comment]
I'm also seeing this compatibility issue with the [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) plugin. The apk lib directory looks like this:

    lib
    |-- arm64-v8a
    |   +-- libsqlc-native-driver.so
    |-- armeabi
    |   +-- libsqlc-native-driver.so
    |-- armeabi-v7a
    |   |-- libsqlc-native-driver.so
    |   +-- libxwalkcore.so
    |-- x86
    |   +-- libsqlc-native-driver.so
    +-- x86_64
        +-- libsqlc-native-driver.so

This issue is also mentioned on this [stackoverflow question]( http://stackoverflow.com/questions/32180713/cordova-crosswalk-native-platform-doesnt-recognized-by-play-store).

Is there any acceptable way to use these two cordova plugins simultaneously?
