### ISSUE TITLE
cordova-plugin-x-toast	 can't pop up message

### ISSUE THREAD

**Issue by ccLadybug** [infil00p/cordova-crosswalk-engine#42]
code：
      $cordovaToast.showShortBottom(response.msg || "未知错误");
logcat：
[ERROR:xwalk_autofill_client.cc(172)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()

**Comment by ccLadybug** [comment]
i find ...   this is other plugin caused error

**Comment by pj-infest** [comment]
Hi.  I have the same error.  
[ERROR:xwalk_autofill_client.cc(172)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()

Can you tell me what plugin error is it.   And how you resolve it.
Thansk
