### ISSUE TITLE
Accessing XWalkView from a custom Cordova Plugin's #initialize 

### ISSUE THREAD

**Issue by aroth** [infil00p/cordova-crosswalk-engine#47]
Is it possible to access the instance of XWalkView from the initialize method of a Cordova plugin? Specifically, I'm looking to call `setUserAgentString`, eg:

```
public class MyPlugin extends CordovaPlugin {
  public void initialize(CordovaInterface cordova, CordovaWebView webView) {
          // xWalkView = ...? 
          // mXWalkView.getSettings().setUserAgentString("Custom UA String Here");
  }
}
```

I realize that I can set `<preference name="xwalkUserAgent" value="..." />` in config.xml, but in this instance I need to append a string to the existing user agent, not replace it entirely.

**Comment by fujunwei** [comment]
You can try to use `<preference name="AppendUserAgent" value="..." />` in config.xml

**Comment by aroth** [comment]
@fujunwei Thank you, that solution certainly gets me closer. However, I need to add bits of custom information into the appended UA string such as the Cordova version. This is why I was hoping it was still possible to set the UA in code. Any thoughts?

**Comment by fujunwei** [comment]
How about add your code in XWalkWebViewEngine::initWebViewSettings?
